import type { Command } from "commander";

export const completionShells = ["bash", "zsh", "fish"] as const;

export type CompletionShell = typeof completionShells[number];

interface CompletionCommand {
  name: string;
  options: string[];
  subcommands: string[];
}

function commandModel(program: Command): CompletionCommand[] {
  const globalOptions = [
    "--help",
    ...program.options
      .map((option) => option.long)
      .filter((option): option is string => option !== undefined),
  ];
  return program.commands.map((command) => ({
    name: command.name(),
    options: [...new Set([
      ...globalOptions,
      ...command.options
        .map((option) => option.long)
        .filter((option): option is string => option !== undefined),
      ...command.commands.flatMap((subcommand) => subcommand.options
        .map((option) => option.long)
        .filter((option): option is string => option !== undefined)),
    ])].sort(),
    subcommands: command.commands.map((subcommand) => subcommand.name()).sort(),
  }));
}

function bashCompletion(commands: CompletionCommand[]): string {
  const commandNames = commands.map((command) => command.name).join(" ");
  const cases = commands.map((command) => {
    const subcommandBlock = command.subcommands.length > 0
      ? `      if [[ $COMP_CWORD -eq 2 ]]; then\n        COMPREPLY=( $(compgen -W "${command.subcommands.join(" ")}" -- "$current") )\n        return\n      fi\n`
      : "";
    return `    ${command.name})\n${subcommandBlock}      options="${command.options.join(" ")}"\n      ;;`;
  }).join("\n");
  return `# Generated by aiba completion bash
_aiba_completion() {
  local current options
  current="\${COMP_WORDS[COMP_CWORD]}"
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${commandNames} --help --version" -- "$current") )
    return
  fi
  case "\${COMP_WORDS[1]}" in
${cases}
    *) options="--help --version" ;;
  esac
  COMPREPLY=( $(compgen -W "$options" -- "$current") )
}
complete -F _aiba_completion aiba
`;
}

function zshCompletion(commands: CompletionCommand[]): string {
  const commandNames = commands.map((command) => command.name).join(" ");
  const cases = commands.map((command) => {
    const subcommandBlock = command.subcommands.length > 0
      ? `      if (( CURRENT == 3 )); then\n        compadd -- ${command.subcommands.join(" ")}\n        return\n      fi\n`
      : "";
    return `    ${command.name})\n${subcommandBlock}      options=(${command.options.join(" ")})\n      ;;`;
  }).join("\n");
  return `#compdef aiba
# Generated by aiba completion zsh
_aiba() {
  local -a commands options
  commands=(${commandNames})
  if (( CURRENT == 2 )); then
    compadd -- $commands
    return
  fi
  case "$words[2]" in
${cases}
    *) options=(--help --version) ;;
  esac
  compadd -- $options
}
compdef _aiba aiba
`;
}

function fishCompletion(commands: CompletionCommand[]): string {
  const lines = [
    "# Generated by aiba completion fish",
    "complete -c aiba -f",
    `complete -c aiba -n '__fish_use_subcommand' -a '${commands.map((command) => command.name).join(" ")}'`,
  ];
  for (const command of commands) {
    if (command.subcommands.length > 0) {
      lines.push(`complete -c aiba -n '__fish_seen_subcommand_from ${command.name}' -a '${command.subcommands.join(" ")}'`);
    }
    for (const option of command.options) {
      lines.push(`complete -c aiba -n '__fish_seen_subcommand_from ${command.name}' -l ${option.slice(2)}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

export function isCompletionShell(value: string): value is CompletionShell {
  return completionShells.some((shell) => shell === value);
}

export function renderCompletion(program: Command, shell: CompletionShell): string {
  const commands = commandModel(program);
  if (shell === "bash") return bashCompletion(commands);
  if (shell === "zsh") return zshCompletion(commands);
  return fishCompletion(commands);
}
